#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${AUTH_DB_NAME};

	CREATE USER ${AUTH_DB_USER} WITH PASSWORD '${AUTH_DB_PASSWORD}';
	GRANT ALL PRIVILEGES ON DATABASE ${AUTH_DB_NAME} TO ${AUTH_DB_USER};
	\c ${AUTH_DB_NAME}
	GRANT ALL PRIVILEGES ON SCHEMA public TO ${AUTH_DB_USER};

    CREATE DATABASE ${APP_DB_NAME};

	CREATE USER ${APP_DB_USER} WITH PASSWORD '${APP_DB_PASSWORD}';
	GRANT ALL PRIVILEGES ON DATABASE ${APP_DB_NAME} TO ${APP_DB_USER};
	\c ${APP_DB_NAME}
	GRANT ALL PRIVILEGES ON SCHEMA public TO ${APP_DB_USER};
EOSQL