/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedWalletConnectedRouteImport } from './routes/_authenticated/_wallet-connected'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedWalletConnectedAdminIndexRouteImport } from './routes/_authenticated/_wallet-connected/admin/index'
import { Route as AuthenticatedWalletConnectedAdminApplicationIdRouteImport } from './routes/_authenticated/_wallet-connected/admin/$applicationId'
import { Route as AuthenticatedWalletConnectedUserIndexRouteImport } from './routes/_authenticated/_wallet-connected/user/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletConnectedRoute =
  AuthenticatedWalletConnectedRouteImport.update({
    id: '/_wallet-connected',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWalletConnectedAdminIndexRoute =
  AuthenticatedWalletConnectedAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedWalletConnectedRoute,
  } as any)
const AuthenticatedWalletConnectedAdminApplicationIdRoute =
  AuthenticatedWalletConnectedAdminApplicationIdRouteImport.update({
    id: '/admin/$applicationId',
    path: '/admin/$applicationId',
    getParentRoute: () => AuthenticatedWalletConnectedRoute,
  } as any)
const AuthenticatedWalletConnectedUserIndexRoute =
  AuthenticatedWalletConnectedUserIndexRouteImport.update({
    id: '/user/',
    path: '/user/',
    getParentRoute: () => AuthenticatedWalletConnectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/$applicationId': typeof AuthenticatedWalletConnectedAdminApplicationIdRoute
  '/admin/': typeof AuthenticatedWalletConnectedAdminIndexRoute
  '/user/': typeof AuthenticatedWalletConnectedUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/$applicationId': typeof AuthenticatedWalletConnectedAdminApplicationIdRoute
  '/admin': typeof AuthenticatedWalletConnectedAdminIndexRoute
  '/user': typeof AuthenticatedWalletConnectedUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_wallet-connected': typeof AuthenticatedWalletConnectedRouteWithChildren
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/_wallet-connected/admin/$applicationId': typeof AuthenticatedWalletConnectedAdminApplicationIdRoute
  '/_authenticated/_wallet-connected/admin/': typeof AuthenticatedWalletConnectedAdminIndexRoute
  '/_authenticated/_wallet-connected/user/': typeof AuthenticatedWalletConnectedUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wallet' | '/admin/$applicationId' | '/admin/' | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wallet' | '/admin/$applicationId' | '/admin' | '/user'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_wallet-connected'
    | '/_authenticated/wallet'
    | '/_authenticated/_wallet-connected/admin/$applicationId'
    | '/_authenticated/_wallet-connected/admin/'
    | '/_authenticated/_wallet-connected/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_wallet-connected': {
      id: '/_authenticated/_wallet-connected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedWalletConnectedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_wallet-connected/admin/': {
      id: '/_authenticated/_wallet-connected/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedWalletConnectedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedWalletConnectedRoute
    }
    '/_authenticated/_wallet-connected/admin/$applicationId': {
      id: '/_authenticated/_wallet-connected/admin/$applicationId'
      path: '/admin/$applicationId'
      fullPath: '/admin/$applicationId'
      preLoaderRoute: typeof AuthenticatedWalletConnectedAdminApplicationIdRouteImport
      parentRoute: typeof AuthenticatedWalletConnectedRoute
    }
    '/_authenticated/_wallet-connected/user/': {
      id: '/_authenticated/_wallet-connected/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof AuthenticatedWalletConnectedUserIndexRouteImport
      parentRoute: typeof AuthenticatedWalletConnectedRoute
    }
  }
}

interface AuthenticatedWalletConnectedRouteChildren {
  AuthenticatedWalletConnectedAdminApplicationIdRoute: typeof AuthenticatedWalletConnectedAdminApplicationIdRoute
  AuthenticatedWalletConnectedAdminIndexRoute: typeof AuthenticatedWalletConnectedAdminIndexRoute
  AuthenticatedWalletConnectedUserIndexRoute: typeof AuthenticatedWalletConnectedUserIndexRoute
}

const AuthenticatedWalletConnectedRouteChildren: AuthenticatedWalletConnectedRouteChildren =
  {
    AuthenticatedWalletConnectedAdminApplicationIdRoute:
      AuthenticatedWalletConnectedAdminApplicationIdRoute,
    AuthenticatedWalletConnectedAdminIndexRoute:
      AuthenticatedWalletConnectedAdminIndexRoute,
    AuthenticatedWalletConnectedUserIndexRoute:
      AuthenticatedWalletConnectedUserIndexRoute,
  }

const AuthenticatedWalletConnectedRouteWithChildren =
  AuthenticatedWalletConnectedRoute._addFileChildren(
    AuthenticatedWalletConnectedRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWalletConnectedRoute: typeof AuthenticatedWalletConnectedRouteWithChildren
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWalletConnectedRoute:
    AuthenticatedWalletConnectedRouteWithChildren,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
